trajectory_execution:
  allowed_execution_duration_scaling: 5.0
  allowed_goal_duration_margin: 5.0
  allowed_start_tolerance: 0.1
  trajectory_duration_monitoring: true

moveit_controller_manager: moveit_simple_controller_manager/MoveItSimpleControllerManager

moveit_simple_controller_manager:
  controller_names:
    - xarm_controller
    - xarm_2finger_gripper_controller
    - xarm_3finger_gripper_controller

  xarm_controller:
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: true
    joints:
        - xarm_7_joint
        - xarm_2_joint
        - xarm_3_joint
        - xarm_4_joint
        - xarm_5_joint
        - xarm_6_joint

  xarm_2finger_gripper_controller:
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: true
    joints:
        - xarm_1_joint

  xarm_3finger_gripper_controller:
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: true
    joints:
        - xarm_8_joint
  